# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  clienteapi:
    image: clienteapi
    build:
      context: .
      dockerfile: Cliente.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
